### ISSUE TITLE
api: combining fastify schemas with joi validation SP 5

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#1064]
### Discussed in https://github.com/openkfw/TruBudget/discussions/970

<div type='discussions-op-text'>

<sup>Originally posted by **laurenzhonauer** September  2, 2021</sup>
In the fastify documentation it is mentioned that validation libraries like joi can be "included" in the schema definition.
Currently we are doing both seperatly, by combining the joi config into the schema definition the api code could be reduced and become more readable and maintainable.

https://www.fastify.io/docs/latest/Reference/Validation-and-Serialization/#using-other-validation-libraries
</div>

**Comment by Stezido** [comment]
TODOs:
- Check fastify solution described in this issue.
- Find a solution to keep swagger/fastify schemas, joi schemas and typescript interfaces in sync. - https://medium.com/swlh/do-not-repeat-yourself-with-swagger-joi-and-typescript-interfaces-a4265e925c18

**Comment by egdmrsy** [comment]
Fastify solution works but not compatible with swagger. The transform property (Schema transform for swagger) needs to be defined when registering the Fastify Swagger plugin on the server. Two problems:
- Recommended npm package "joi-to-json" creates compilation issues. Somehow its code cannot compile due to import issues in source code.
- Global Schema transform is not what we are looking for but rather local transform would be useful. Documentation states that for local transform one has to define the transform function under fastify.get(path, { config: { swaggerTransform: (...) => {...}}}) route options but typescript throws "swaggerTransform" does not exist in type...

**Comment by galethil** [comment]
Closed due to complexity
