### ISSUE TITLE
P2P_PORT refers to 2 ports

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#1117]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

P2P_PORT refers to 2 PORTS at once.
it defines the own P2P_PORT and the one of the master/alpha node it wants to connect to.
Maybe it is intentional since the network must be on the same port in each organization.
If not, changing it would enable testing 2 nodes on the same machine.

**Comment by mayrmartin** [comment]
will be added when especially requested.  this will not be a breaking change since the implementation will check if both or only one variable are set. if only one variable is set both ports will be set by the implementation to the same value. if both are set both ports will be set to the corresponding value
