### ISSUE TITLE
Bug in document names

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#1153]
### Discussed in https://github.com/openkfw/TruBudget/discussions/1146

<div type='discussions-op-text'>

<sup>Originally posted by **BorisFromBE** May 13, 2022</sup>
It is currently impossible to upload documents using letters with accents to a workflow item, the error message given when trying to is also inexplicit, stating « You are not authorized to perform all listed actions ». 

We aim to allow the application to handle document names with accents.
</div>

**Comment by georgimld** [comment]
Issue will be closed since the bug could not be reproduced. Documents with different accents and special characters could be uploaded without problems, as can be seen in the screenshot below:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/48566702/236211760-e1395a76-35f2-47f6-b174-0448b965d27e.png">
