### ISSUE TITLE
Reassigning wf item removes permissions

### ISSUE THREAD

**Issue by schoel-bis** [openkfw/TruBudget#1174]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

I suppose this is supposed to be a feature rather than a bug, but it causes a conflict for us:

When a regular user reassigns a workflow item, that user looses all permissions on that workflow item, except view permission. This is not implemented as a set of calls from the frontend, but appears to be a property of the backend, as also a single call to the workflowitem.assign API will trigger this behaviour.

The same is not true if root reassigns, i.e. in that case the user that is unassigned will retain all his permissions.

This is problematic for us as we need a user that can manage all workflow items, including closing them. A regular user will not work because of the issue outlined above, root won't work because he cannot close at all.

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
| Frontend        | v1.29.1  |
| API             | v1.29.1  |
| Blockchain      | v1.?.?  |
| Export-Service  | v1.?.?  |
| Email-Service   | v1.?.?  |
| Storage-Service | v1.?.?  |

**Comment by daniel-arnauer** [comment]
In the next release (2.1.0), the root user will regain permissions to close all workflowitems (and other entities). The issue in the dialog has been partially fixed by adding a warning about overwriting permissions to the user with https://github.com/openkfw/TruBudget/pull/1216

The next thing that should be done is to implement a better workflowitem batch dialog to add instead of override permissions.

This issue relates to #1189
