### ISSUE TITLE
Group permission issues on project/subproject level

### ISSUE THREAD

**Issue by Malick-Niang** [openkfw/TruBudget#1189]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

### How to reproduce 🕹

We created a project and a few subprojects in it and gave some users the view right on them. After that we created a group where we put all those users. Next, some workflow items were created and the view right given to the group. In result, the users lost the view permission on the subprojects and these subprojects disappeared from the subprojects list. We had to give the view rights on the subproject level to the group.

## Your Environment 🌎

| Tech            | Version |
| --------------- | ------- |
frontend | 1.28.1 |  
api | 1.29.0 |
blockchain | 1.28.1 | 
multichain | 2.1.2 | 
emailService | 1.28.1 | 
exportService | 1.28.1 | 
storage | 1.28.1 | 
<html>
<body>

</body>
</html>

**Comment by daniel-arnauer** [comment]
Hello,

I think you used the multi-selection (see screenshot below) to edit the permission of the workflowitem (instead of the according workflowitem permissions dialog). If you use the multi selection and edit the permission, all permission will be overwritten by the current selected. If you want to remove or add permissions only, you should the permission dialog of each workflowitem instead. 

To make it easier to understand for the user, I will edit the current mutli-select dialog to have a better overview.

![Screenshot 2022-07-04 at 14 59 18](https://user-images.githubusercontent.com/59825636/177161744-9528134e-4bbd-4f85-99e4-5a98e739a326.png)
