### ISSUE TITLE
api: errors are not thrown/catched correctly - this leads to difficult to read error messages

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#131]
In GitLab by @Stezido on Mar 14, 2019, 14:39

**Comment by Stezido** [comment]
The error status codes in a response body have to be more specific I suggest we use own status codes. 
For example the endpoint user.authenticate can fail due to:

- user does not exist (Not Found)
- wrong password (Not Authenticated)
- user is not from the node's organization (Decryption Failed)

So in the User Not Found case the response is a 400 Bad Request with following response body:
`{
code: 1234
message: "authentication failed: user does not exist"
}`
