### ISSUE TITLE
Exchange rate API not allowed by NGINX config

### ISSUE THREAD

**Issue by mayrmartin** [openkfw/TruBudget#1487]
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 😯

In PR #1406 (closed) the endpoint to fetch the exchange rates was made dynamically. This leads to an error when the access point is not set to the default value as it is not marked in the NGINX config as an allowed host.
Furthermore, there is an issue regarding older releases. 
There was a change regarding the endpoint where we fetch the currency per default. This change was made by changing the URL but not reflecting the changes in the NGINX config.  This issue was reported on a Trubduget Sandbox which runs on 1.30.

Proposed ToDos:

- if the exchange URL should be dynamic, allow the domain in the NGINX config by making it also dynamic
- Evaluate how this issue impacts older versions and how big the impact is

**Comment by SamuelPull** [comment]
Issue is not with the nginx config. csp header inside the config is correctly set to  REACT_APP_EXCHANGE_RATE_URL value.
However, frontend container is always using the predefined forex url, because config is fixed at build time, not runtime.
What's missing is a default in env.js and its substition in configureServer.sh
