### ISSUE TITLE
Analysis of alternatives to multichain

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1559]
- [x] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡
Lets discuss possible alternatives to replace MultiChain

**Comment by jzakotnik** [comment]
Some first ideas:
https://celo.org/
https://polygon.technology/

**Comment by RonMath** [comment]
Some additional ideas:
https://besu.hyperledger.org/
https://cosmos.network/

**Comment by egdmrsy** [comment]
Also take a look at [Polkadot](https://polkadot.network/features/parachains/) / [Kusama](https://kusama.network) and their use of Parachains. 

Parachains are basically L-1 chains developed via Polkadot's SDK Substrate with their own design and can be run on public or private networks with separate token economy and governance model. The advantage of it is that it is also by default Polkadot cross-chain compatible. Using the Polkadot's architecture, once connected to the Polkadot's network, parachains can communicate with each other and exchange any info, credentials, their own native tokens and smart contract calls.

Difference between Kusama and Polkadot is that Kusama is faster, easier to deploy a parachain and costs less to bind a parachain to main network. Mostly for development and testing purposes.

Not everyone can deploy parachain on Polkadot, there are slots in intervals, for that a parachain has to be chosen.

**Comment by mayrmartin** [comment]
A while ago we had a look at https://immudb.io/, I liked the idea & what they are doing + they claim to be GDPR compliant which is a plus.

**Comment by egdmrsy** [comment]
Certain features to pay attention to when choosing an alternative (open for debate):

- Immutability and data verifiability
  - Important for audit / transaction trail 
  - Cryptographically verifiable
- Permissioned Distributed Network capabilities (P2P) (Further discussion needed to compare following points)
  - Data Consistency and integrity
  - Fault Tolerance
  - Availability
- Possibly open-source with active community / maintainers.
  - Avoiding technical debt
- If there is smart contract capability, check how to utilise them, if possible. Otherwise it might be just an overhead.

**Comment by SamuelPull** [comment]
- Hyperledger Fabric ?
- Corda R3 - seems like a good fit usecase wise, but uses Java/Kotlin
