### ISSUE TITLE
PoC: Avoid using API calls to connect node, brainstorm alternatives (e.g. key via eMail)

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1700]
Add a new feature in the `/nodes` dashboard to manually add a new node to the network (pending approval) -> this would replace the current `registerNodeAtAlpha` request done by the blockchain.

So steps would be:
1. beta node starts the node (no permissions yet to enter network)
2. beta copies its own address from the startup logs (todo: make sure the logs are displayed propperly)
3. beta sends the address and orga name to the alpha admins via email
4. alpha node admins enter the beta details in the new UI component on the `/nodes` tab #1728

**Comment by SamuelPull** [comment]
Some edge cases to handle:

When a user is registering a new node and organization 
- [ ] and makes a mistake in organization name
- [ ] and makes a mistake in node address
- [ ] makes a mistake in both.

Either of these mistakes results in irrecoverable error. Correct address with incorrect orga name cannot be approved nor re-registered with corrected orga name. 
If the user makes a mistake in address string, and adds the correct address afterwards, approval fails, because an array of addresses is sent to the node. One rotten apple spoils the barrel.
Currently there is no mechanism to recover from these errors. I think we shouldn't release this feature without an option to correct user mistakes.

**Comment by jzakotnik** [comment]
@SamuelPull why is the old address sent again for approval? This looks like a tricky situation. First reaction was we solve imaginary scaling problems, but if a mistake is always used for the complete array for approval, I agree with you.. Not sure what the solution space looks like?

**Comment by jzakotnik** [comment]
Awesome meme :-)
The question is at which stage we need to solve the scaling problems. So far, each node connection is pretty manual, so if there's a mistake it's easy to tear everything down and up again.

The more probable situation might be that a organisation renames itself and then the old name is carved in stone/blockchain forever. So in that case we would migrate to a new node with a new organisation name and tear down the old?
