### ISSUE TITLE
Add option to validate documents on the client side

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#1708]
- [x] The feature was discussed in [discussions](https://github.com/openkfw/TruBudget/discussions) of this repository.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Description 💡
It might be useful to validate documents hashes on the client side, so that the docs don't leave the browser, this would increase security for sensitive documents. 
Right now the hashes are validated in the api but I think it could also be checked in the frontend.

**Comment by SamuelPull** [comment]
Document validation creates a notification. Is this a required feature? I don't see the purpose. Anyhow, maybe the notifications for document validation were not meant to be implemented, because the translation key-value is not implemented.
<img width="698" alt="Screenshot 2024-03-11 at 10 56 23" src="https://github.com/openkfw/TruBudget/assets/26326794/6a4b95fb-27fa-4e60-ad44-019af54908f3">
