### ISSUE TITLE
Set a fingerprint for a file linked in TruBudget

### ISSUE THREAD

**Issue by jzakotnik** [openkfw/TruBudget#1862]
If a file is added to a workflow item as a link, TruBudget cannot calculate the fingerprint because it might not have access to the linked file.
One of the users requested that a fingerprint for a linked file can be added (manually).

**Comment by galethil** [comment]
@jzakotnik this is an interesting request. 
What will be the use case of manual fingerprint? Since for files not publicly available on the internet uploader will need to create fingerprint locally and set it manually in TruBudget and another user will need to download the file and then validate the fingerprint again locally. If this is the case, users can simply add the fingerprint hash into the name field like "ReportJan2024.docx (fingerprint g7d63g4fi3gfg34fg384fg348fgbkc)".

**Comment by jzakotnik** [comment]
@galethil I think the use case is easier. It simply means, people exchange documents outside of trubudget (for whatever reason, regulatory or something else), but they would like to trace which version was the agreed version. So like the `validate` button at the moment already creates a fingerprint, it would be nice to attach this to a link that is entered as a document.

**Comment by galethil** [comment]
So to summarise the request is:
- add 3rd optional field "fingerprint" when adding external document link
- user will have possibility to fill this field when adding new external document link
- fingerprint will be displayed next to the link in TruBudget
- it will NOT be possible to validate external link in TruBudget directly
- user can just use this fingerprint to validate external document outside of TruBudget.

Is this correct?

**Comment by jzakotnik** [comment]
@galethil I believe that no user can actually calculate the hash and input it. My proposal would be that the user can insert the link but the assumption is that the user also has access to the link. So she would have 

- an `Add fingerprint` button
- this opens the file dialog
- she can upload the document
- the fingerprint is calculated in memory and the document deleter in memory again
- the fingerprint is saved together with the link

**Comment by galethil** [comment]
@jzakotnik I think I understand now.
So that a user adds an external link. Then he clicks on add fingerprint, and manually uploads the document that the link is pointing towards. Hash is created and stored in chain.
Then other user will download the file from the external link. And this other user will be able to verify the downloaded document, by clicking "verify hash" and uploading document to the TruBudget, where it will be checked.
This is possible, only limitation will the the total size of the file.
