### ISSUE TITLE
ui: Create dropdown menu for sources of finance

### ISSUE THREAD

**Issue by mathiashoeld** [openkfw/TruBudget#226]
Create drop down menu for sources of finance when creating a project. The selectable instances should be provided by an external source.

**Comment by gonzochic** [comment]
This is an issue which is very specific to a certain use-case. Either we add the functionality to globally manage sources of finance in TruBudget or we expect from the user that he is able to provide the correct information when creating a project.

Integrating external sources has a high complexity due to the need of a "general" interface which fits "everybody".

**Comment by mathiashoeld** [comment]
the drop down menu will be implemented in #228 for subprojects and as mentioned above, there is currently no plan to implement this globally. this issue will therefore be closed.
