### ISSUE TITLE
ui: Suggest adding permissions when assigning a (sub-)project

### ISSUE THREAD

**Issue by phpai** [openkfw/TruBudget#23]
In GitLab by @kevinbader on Jul 30, 2018, 10:40

## Problem

When assigning someone to a project or subproject, the assignee is not granted any permissions. This should stay that way, but there is an unfortunate side effect: it may happen that an assignee doesn't even have permissions to _view_ the project or subproject she's assigned to, which clearly is unexpected behaviour to the user.

## Proposed Solution

Instead of adding any automatic permission changes to `*.assign` intents, the UI should check whether the current assignee has all expected permissions. If not, the UI should offer to change the assignee's permissions, using a modal dialog. If the current user is not allowed to grant additional permissions, the check doesn't need to be done and the dialog should not appear.

**Comment by phpai** [comment]
In GitLab by @kevinbader on Aug 10, 2018, 11:43

We'll need to tackle dialogs more broadly than this. For example, this will hardly remain the only "convenience" dialog we need, and there is also the need for "do you really want to do this" dialogs in various places.

-> rescoping to a later beta release of 1.0.0

**Comment by Stezido** [comment]
Yes we should implement the permission checks on UI-level. As an addition to the idea of the modal dialog I think if the user which is assigning has no permissions to grant additional permissions at least a "do you really want to do this" dialog should open with warnings that the assigned user would not see the project she would be assigned to. Otherwise we have the same initial problem and unexpected behaviour. 

I also agree with the broadly dialogs!
