### ISSUE TITLE
ui: budgets on subproject analytics contain open workflow items

### ISSUE THREAD

**Issue by gonzochic** [openkfw/TruBudget#230]
When calculating the Assigned and Disbursed Budget on the subproject analytics screen, we should only take closed workflow items into account. For project analytics the calculation is correct.

https://github.com/openkfw/TruBudget/blob/e835c5ca8a19d2590fb32841b89e491d21cf1579/frontend/src/sagas.js#L1264-L1278

**Comment by Stezido** [comment]
We already take only closed workflow items into account on subproject level. The code snippet belongs to get project KPIs instead of get subproject KPIs. See the right snippet below.

https://github.com/openkfw/TruBudget/blob/e835c5ca8a19d2590fb32841b89e491d21cf1579/frontend/src/sagas.js#L1362-L1374

**Comment by Stezido** [comment]
The project KPIs should be updated instead of subproject KPIs.
