### ISSUE TITLE
Translations ENG->French

### ISSUE THREAD

**Issue by lennartploen** [openkfw/TruBudget#312]
Info-button on worklow item level : 
overview -> Sommaire
Documents -> Documents
History -> Historique
Workflow item details ->Détails du workflow item

In this historic:
French: Last event reached -> dernier évènement atteint

Subproject level : 
Subproject currency -> Devise la composante 

Analytics screen on workflow level: 
Projected Budgets Distribution -> Répartition du budget total

General:
- "subproject" (sous projet) should be replaced by "component" (composante) everywhere 
- Please review all non translated words you find via "FRENCH: ..."
- Excel exports are available in English only : Possible to translate them into French?

**Comment by mathiashoeld** [comment]
@lennartploen thanks for the translations!

### ad _Please review all non translated words you find via "FRENCH: ..." 
may i ask you to translate the following:_

- Projected budget of project {0} was deleted 
- Projected budget of project {0} was updated
- Projected budget of subproject {0} was deleted 
- Projected budget of subproject {0} was updated
- No events _(note: this is for the case where there is no history available for a given project/subproject/workflowitem. this should not happen anyway since the creation event should always be available, but just in case)_

### ad _Excel exports are available in English only : Possible to translate them into French?_
See issue #304

**Comment by mathiashoeld** [comment]
additional translations done in #314 and #315
