### ISSUE TITLE
travis: Don't push docker images for pull requests

### ISSUE THREAD

**Issue by mathiashoeld** [openkfw/TruBudget#319]
# Situation
When creating a pull request, the travis CI pushes the built docker images to a private docker registry. This is not ideal since the pipeline will fail if the pull request is created by someone who is not a maintainer or contributor of the repository. 

# Solution
Perform the docker build to check if the build succeeds, but don't push the images to the private repository for pull requests. The process should stay the same for tagging and pushes to master, where the images are tagged and uploaded to the public docker registry.

**Comment by phpai** [comment]
The job responsible for pushing docker images uses secure environment variables (credentials to docker repo). These env variables are not available for PRs sent from forks, due to [travis security restriction](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions).

**Updated Solution**
Docker builds and E2E tests disabled for PR from forks.
Current workaround: Reviewer needs to execute them manually.

New issue opened for discussing e2e approach for outside contributors

**Comment by phpai** [comment]
disabled docker builds and e2e for forks in 0ccda3ac271411ec85a7bb8733a8b699949e175f
