### ISSUE TITLE
ui: Granting permissions on a resource for groups doesn't work properly 

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#440]
### Description
Resource permissions granted for groups are ignored.
Tested examples:
- redaction of  workflowitems with view workflowitem permission
- Unable to view/grant/revoke permissions with view/grant/revoke permissions permission on workflowitem level

**Comment by daniel-arnauer** [comment]
**One bug in subproject-level:**
As admin (mstein) at subproject-level "Set permissions for [subproject-name]"  in "View permissions": when you set "View subproject details" (the loupe icon) for a user (eg.: jdoe)
then trubudget automatically adds the permission "View subproject overview". After this, when you disable 
"View subproject details" (the loupe icon), the overview line is still there. Gernerally, it should be disabled altough the user
still have the permission "View subproject details" (without seeing it because the element to view it has been disabled).

**Comment by daniel-arnauer** [comment]
**Antother Bug**
The fields "Grant subproject permissions" and "Revoke subproject permissions" have no affection when used with groups (it only works when you specify a person directly)

**Comment by daniel-arnauer** [comment]
Another Bug:
When assigning an user to a group, the group is only added after the user makes a re-login (the group data is only fetched at the beginning)
