### ISSUE TITLE
prov: The provisioning exits when api is not reachable - SP 3

### ISSUE THREAD

**Issue by Stezido** [openkfw/TruBudget#561]
### Description
If the provisioning is started without having started the api the prov exits. The prov should retry instead.
While prov the prov should not generate any errors which is currently not the case.
Also sometime the prov is getting an error during prov and disconnects - it waits for 20 secs and go on without any problem again.

### TODO
Reproduce the error where prov exits without retrying.
Reproduce the error/s while provisioning.
Check solution ;)

**Comment by Stezido** [comment]
As the following image shows there is still an issue with the provisioning exiting unexpected.
![image](https://user-images.githubusercontent.com/5485771/100872472-2846b180-34a2-11eb-8eb8-94acca2843b8.png)

**Comment by SamuelPull** [comment]
@Stezido I don't think this is the same issue as the one I reproduced. According to provisioning source, Error with code 500 is supposed to exit provisioning immediately, though error has `undefined` property `err.status`. 
`provisioning/src/lib.js > withRetry`

Also that function hides an obvious bug, string template inside double quotes. It's reasonable to assume it might contain some other bugs as well. I think it merits careful rework and testing.
<img width="731" alt="Screenshot 2020-12-04 at 12 36 08" src="https://user-images.githubusercontent.com/26326794/101160073-af289500-362e-11eb-9958-d1c5b0e5c4f9.png">

Judging from error message, the only place such error could originate is
`api/src/service/RpcClient.ts` at `response = new RpcError(500, "No Response", {}, error.message);`
[Maybe it's unrelated, method containing that line is flagged by eslint rule `no-async-promise-executor`.]

Since error originates in calling the `invoke` method of `RpcClient`, I think API is reachable, and reached by provisioning, and the error message is misleading. There might be an answer in API logs. Every call of `invoke` is supposed to be logged.

On the provisioning side, there might be access to more information via `err.stack` or `err.data.error.stack`, when the error is an `RpcError`.

How did you manage reproduce this bug? Thanks.
