### ISSUE TITLE
Currency displayed on component page

### ISSUE THREAD

**Issue by Malick-Niang** [openkfw/TruBudget#646]
On component page, the currency displayed for all amounts is "€" even if another currency was selected during item creation.

- [ x] The issue is present in the latest release.
- [ x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Table of workflow items displays € instead of chosen currency.

## Steps to Reproduce 🕹

Steps:

1. Create a workflow item 
2. Choose "$" as currency while adding an amount
3. validate
4. Look at the table

## Your Environment 🌎

| Tech           | Version |
| -------------- | ------- |

frontend | 1.16.0 | 
api | 1.16.0 |
blockchain | 1.16.0 |
multichain | 2.0.1 |
emailService | 1.16.0 |
exportService | 1.16.0 |

**Comment by SamuelPull** [comment]
@Stezido Maybe using symbols of currencies should be replaced by displaying three letter codes, where applicable ISO 4217 codes? Dollar symbol is used for several currencies, and some currencies don't have a symbol, e.g. XOF West African Franc? Perhaps KfW could provide a list of codes they use?

- EUR 1,000,000.00 instead of 
-    €  1,000,000.00 

<img width="265" alt="Screenshot 2020-11-26 at 15 51 26" src="https://user-images.githubusercontent.com/26326794/100365909-60607700-3000-11eb-9103-8c77383fb444.png">

**Comment by SamuelPull** [comment]
@Malick-Niang Table of workflow items always displays the amount in EUR using currency conversion rate entered.
<img width="756" alt="Screenshot 2020-12-02 at 13 19 39" src="https://user-images.githubusercontent.com/26326794/100871876-3d6f1080-34a1-11eb-9cd3-22307d950d69.png">
<img width="650" alt="Screenshot 2020-12-02 at 13 19 53" src="https://user-images.githubusercontent.com/26326794/100871881-3ea03d80-34a1-11eb-86a9-cd46befc71fa.png">

**Comment by Stezido** [comment]
@SamuelPull you're right to be consistent we should change the symbol into the letter code.

@Malick-Niang I think this is not a bug - The workflowitems always show their budget in the currency of the subproject.

**Comment by Stezido** [comment]
This Issue will be closed. You can reopen it if a follow up is needed
