### ISSUE TITLE
Create workflowitem error because of missing permissions - 3SP

### ISSUE THREAD

**Issue by georgimld** [openkfw/TruBudget#738]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

A user is sometimes not able to create a workflowitem because if the following error:
![create workflowitem error](https://user-images.githubusercontent.com/48566702/104923094-ddbebd00-599b-11eb-82c4-052109f1167f.png)
This happens when the user creating the workflowitem has the "create workflowitem" permission but does not have the "project view permissions" and "subproject view permissions" permission. The problem probably happens because the workflowitem assignment is not successful, which happens during the workflowitem creation.

## Steps to Reproduce 🕹
Steps:

1. User A creates a project and a subproject
2. User B is given the following permissions:

- view project in overview
- view project details
- view subproject in overview
- view subproject details
- create workflowitem

3. User B tries to create a workflowitem (assignee is not important, can be User B or A or some other user)
4. After user clicks on "Submit", the error is shown

## Solution
When the "create workflowitem" permission is assigned to a user, the project & subproject "view permisssions" and "grant permissions" permissions should be automatically assigned to the user (currently only the "view overview" and "view details" permissions are assigned)

**Comment by daniel-arnauer** [comment]
The problem is, when you set the permission createWorkflowitem for an user, the confirmation dialog generates following additional action: 

- Project: view summary
- Project: view details
- Subproject: view summary
- Subproject: view details


To create a workflowitem, a user also needs project.listPermission and subproject.listPermission.

To resolve this issue, these two permission (project.listPermission and subproject.listPermission) must be added
