### ISSUE TITLE
Rename environmental variable "PORT" SP 0.5

### ISSUE THREAD

**Issue by daniel-arnauer** [openkfw/TruBudget#999]
## Description 😯

The env var PORT is used in the API and excel-export project to define the port. This is confusing when using an .env file for multiple services (like the .env file in dev or operation setup) .

## Solution
Rename PORT in API to API_PORT and in excel-export to EXCEL_EXPORT_PORT.

Also rename API_HOST to MASTER_API_HOST and API_PORT (the current) to MASTER_API_PORT and API_PROTO to MASTER_API_PROTO

This is a breaking change for existing deployments!

## Your Environment 🌎

v1.26.0

**Comment by Stezido** [comment]
We want to use `PORT` for every service as own port env var name.
Renaming API_HOST would lead to even more confusion because `API_HOST` is the external api host of another network for the blockchain service. When a node is started as "master"- node it wouldn't need the MASTER_API_HOST env var - that's confusing

**Comment by georgimld** [comment]
keep format of env vars for enabled services consistent: 

e.g. DOCUMENT_FEATURE_ENABLED= true vs DOCUMENT_SERVICE=enabled

Should always be: XX_SERVICE_ENABLED=true
